name: Auto Label

on:
  pull_request:
    branches: ["main"]
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  handle-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge Label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const labelToAdd = "automerge";
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: [labelToAdd]
            });