on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  iOSWorkflow:
    uses: ./.github/workflows/ios.yml
    
  Lint:
    uses: ./.github/workflows/swift-lint.yml
    
  AutoMerge:
    needs: [iOSWorkflow, Lint]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}