name: iOS workflow

on:
  workflow_call:
    
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    env:
      XCODE_VERSION: "16.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: |
          echo "Setting Xcode version to $XCODE_VERSION"
          sudo xcode-select -s "/Applications/Xcode_$XCODE_VERSION.app"
          xcodebuild -version
        
      - name: Show Xcode version
        run: xcodebuild -version
        
      - name: List available schemes
        run: xcodebuild -list
        
      - name: Set Simulator Device
        id: set_device
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          if [ -z "$device" ]; then
            echo "Error: No available iOS Simulator found!"
            exit 1
          fi
          echo "DEVICE_NAME=$device" >> $GITHUB_ENV
          echo "Using device: $device"

      - name: Run Unit Tests
        run: |
          xcodebuild test -scheme "TodoAppUnitTests" -destination "platform=iOS Simulator,name=${DEVICE_NAME}"

      - name: Run UI Tests
        run: |
          xcodebuild test -scheme "TodoAppUITests" -destination "platform=iOS Simulator,name=${DEVICE_NAME}"